-- Restante da linha híbrida/elétrica Toyota e Honda que faltava no catálogo
-- (usuário apontou os modelos em 11/09/2026). Pesquisado e verificado na
-- mesma sessão, direto em fonte oficial (PDF de ficha técnica de cada
-- marca + preço cruzado com imprensa quando o site não expõe o valor no
-- HTML estático).
--
-- Honda Prelude incluído a pedido do usuário mesmo em pré-venda (até o final
-- de setembro/2026) — tem preço oficial firme (R$380 mil, anunciado no
-- Festival Interlagos) e é híbrido de verdade. Único ponto em aberto: o
-- catálogo PDF oficial de consumo da Honda (baixado em 11/09/2026) lista só
-- os componentes separados (143cv combustão / 184cv elétrico — os MESMOS
-- números do Civic Advanced Hybrid, sem uma linha de "potência combinada").
-- Os 203cv usados aqui vêm de multiplas fontes de imprensa (incl. AutoData,
-- publicação do setor) reportando de forma consistente esse valor como
-- potência combinada — não é o mesmo tipo de erro do caso Kicks (lá não
-- havia NENHUMA fonte, nem site oficial, confirmando híbrido). Vale
-- reconfirmar quando a Honda publicar uma ficha técnica mais completa.
--
-- Rode isso uma vez no SQL Editor do Supabase. Depois:
-- `node scripts/generate-fallback-snapshot.mjs` + commit do carsFallback.json.

insert into cars (
  id, name, brand, category, price, power_cv, torque_nm, battery_kwh, battery_chem,
  motor_type, range_km, accel, ground_clearance, trunk_l, weight_kg, wallbox, ac_kw, dc_kw,
  airbags, warranty, fuel_type, verified, price_verified_date, maintenance_interval,
  maintenance_first_cost, maintenance_km_base, maintenance_total_cost, consumption_kwh_100,
  tech_notes, image_url, video_url, personas
) values
(
  'toyota-yaris-cross-hybrid',
  'Toyota Yaris Cross Hybrid XRE',
  'Toyota',
  'SUV compacto híbrido',
  172390,
  111,
  141,
  null,
  null,
  'Híbrido HSD (Hybrid Synergy Drive) — motor 1.5L Dual VVT-i Flex + dois motores elétricos (MG1/MG2)',
  null,
  null,
  208,
  400,
  1270,
  null,
  null,
  null,
  null,
  '5 anos veículo / 8 anos sistema híbrido',
  'HEV',
  true,
  '11/09/2026',
  null,
  null,
  null,
  null,
  null,
  'Versão de entrada híbrida (XRE Hybrid) — existe também a XRX Hybrid, mais equipada, R$189.990. Ficha oficial (catálogo PDF Toyota, baixado do site em 11/09/2026): motor 1.5L 91cv/5.500rpm + 12,3kgf.m etanol, motor elétrico 80cv/14,4kgf.m. Diferente do Corolla Cross Hybrid e do Corolla Hybrid, aqui a Toyota PUBLICA uma potência combinada explícita: 111cv — é essa a usada aqui (torque combinado não é publicado; o valor registrado é só do motor elétrico). Consumo: dado não encontrado nesta ficha especificamente.',
  'https://media.toyota.com.br/0990e340-6ac1-4a5d-bc5f-92b9317ba387.jpeg',
  null,
  '{"urbano":5,"familia":3,"aventura":2,"performance":2,"custo":5}'::jsonb
),
(
  'toyota-corolla-hybrid',
  'Toyota Corolla GLi HEV',
  'Toyota',
  'Sedã médio híbrido',
  194790,
  101,
  142,
  null,
  null,
  'Híbrido HSD (Hybrid Synergy Drive) — motor 1.8L VVT-i Flex + dois motores elétricos (MG1/MG2)',
  null,
  null,
  148,
  470,
  1425,
  null,
  null,
  null,
  null,
  '5 anos veículo / 8 anos sistema híbrido',
  'HEV',
  true,
  '11/09/2026',
  null,
  null,
  null,
  null,
  null,
  'Versão de entrada híbrida do sedã Corolla (GLi HEV) — existe também a Altis Hybrid Premium, mais equipada, R$210.090. Mesmo conjunto motor+bateria do Corolla Cross Hybrid (plataforma compartilhada): motor 1.8L 101cv/5.200rpm + 14,5kgf.m etanol, motor elétrico 72cv/16,6kgf.m — a Toyota também NÃO publica potência combinada pra esta ficha (mesma ressalva do Corolla Cross Hybrid: os 101cv aqui são só do motor a combustão).',
  'https://media.toyota.com.br/99e72450-f1f1-4244-9241-18bcf3808306.webp',
  null,
  '{"urbano":4,"familia":4,"aventura":1,"performance":2,"custo":4}'::jsonb
),
(
  'toyota-bz4x',
  'Toyota bZ4X AWD',
  'Toyota',
  'SUV médio premium',
  422420,
  343,
  269,
  73.1,
  'Íon de lítio',
  '100% elétrico — dois motores elétricos AWD (227cv dianteiro / 120cv traseiro), plataforma e-TNGA',
  361,
  null,
  180,
  452,
  2110,
  null,
  22,
  150,
  null,
  '5 anos veículo (garantia de bateria não confirmada nesta ficha)',
  'BEV',
  true,
  '11/09/2026',
  null,
  null,
  null,
  null,
  20.25,
  'SUV 100% elétrico da Toyota — não é híbrido, entra no catálogo por completar a lacuna que o usuário apontou (linha Toyota inteira: Yaris Cross Hybrid, Corolla Hybrid, Corolla Cross Hybrid e bZ4X). Ficha oficial (catálogo PDF Toyota "bZ4X MY26", baixado em 11/09/2026): motor dianteiro 227cv/27,4kgf.m + motor traseiro 120cv/17,3kgf.m, potência total 343cv (publicada explicitamente pela Toyota). Torque registrado aqui é só do motor dianteiro (269Nm) — a Toyota não soma os dois torques numa ficha única. Bateria 73,1kWh, autonomia 361km Inmetro. Consumo (20,25 kWh/100km) é CALCULADO por nós (73,1kWh ÷ 361km × 100) — a Toyota não publica esse número diretamente. Carregamento AC 22kW / DC 150kW. Vão livre e peso confirmados; airbags e garantia de bateria não encontrados nesta ficha específica.',
  'https://media.toyota.com.br/3bd14f56-d6f3-4ca9-a7e1-fff2e4034234.jpeg',
  null,
  '{"urbano":3,"familia":4,"aventura":3,"performance":4,"custo":1}'::jsonb
),
(
  'honda-civic-advanced-hybrid',
  'Honda Civic Advanced Hybrid',
  'Honda',
  'Sedã médio híbrido',
  266500,
  184,
  315,
  1.05,
  'Íons de lítio',
  'Híbrido e:HEV — motor 2.0L DI DOHC (gerador) + motor elétrico de tração',
  null,
  null,
  null,
  495,
  null,
  null,
  null,
  null,
  8,
  '3 anos veículo / 8 anos sistema híbrido',
  'HEV',
  true,
  '11/09/2026',
  null,
  null,
  null,
  null,
  null,
  'Único trim de Civic vendido no Brasil (Advanced Hybrid) — sem versão a combustão pura na linha atual. Mesmo motor elétrico (184cv/32,1kgf.m — 315Nm) do CR-V e do Accord híbridos, motor a combustão ligeiramente diferente por modelo (aqui 143cv/19,1kgf.m gasolina). Ficha oficial (catálogo PDF Honda, baixado em 11/09/2026) e imprensa especializada concordam: 184cv é tratado como a potência combinada/de sistema pra esta configuração FWD (sem motor traseiro adicional como no CR-V AWD, cujo combinado de 207cv inclui o eixo traseiro). Preço R$266.500 (checado em 11/09/2026) — vendas baixas reportadas no mercado brasileiro (imprensa cita ~34 unidades em 2026), mas o modelo segue oficialmente à venda. Consumo Inmetro: 18,4 km/l cidade / 15,9 km/l estrada gasolina.',
  'https://www.honda.com.br/automoveis/sites/hab/files/2026-05/civic.webp',
  null,
  '{"urbano":4,"familia":3,"aventura":1,"performance":3,"custo":3}'::jsonb
),
(
  'honda-accord-advanced-hybrid',
  'Honda Accord Advanced Hybrid',
  'Honda',
  'Sedã grande híbrido',
  332400,
  184,
  334,
  1.05,
  'Íons de lítio',
  'Híbrido e:HEV — motor 2.0L DI DOHC (gerador) + motor elétrico de tração',
  null,
  null,
  null,
  574,
  1625,
  null,
  null,
  null,
  8,
  '3 anos veículo / 8 anos sistema híbrido',
  'HEV',
  true,
  '11/09/2026',
  null,
  null,
  null,
  null,
  null,
  'Único trim de Accord vendido no Brasil (Advanced Hybrid), versão única de cor (Preto Cristal Perolizado) na linha 2026. Mesmo motor elétrico (184cv/34,1kgf.m — 334Nm) do CR-V e do Civic híbridos; combustão 146cv/19,2kgf.m gasolina. Ficha técnica de especificações (dimensões, motor, porta-malas 574L) vem de um catálogo PDF datado de agosto/2023 — mais antigo que o dos outros modelos —, mas os números batem exatamente com o que a imprensa reporta pra linha 2026 (checado em 11/09/2026), incluindo os 574L de porta-malas, o que dá confiança de que a ficha técnica em si não mudou, só o ano/preço. Preço R$332.400 (linha 2026, checado via imprensa em 11/09/2026 — o site oficial não expõe o valor no HTML estático). Consumo Inmetro: 17,8 km/l cidade.',
  'https://www.honda.com.br/automoveis/sites/hab/files/2025-10/accord.webp',
  null,
  '{"urbano":2,"familia":4,"aventura":1,"performance":3,"custo":1}'::jsonb
),
(
  'honda-prelude',
  'Honda Prelude',
  'Honda',
  'Cupê esportivo híbrido',
  380000,
  203,
  315,
  1.05,
  'Íons de lítio (mesma plataforma híbrida do Civic — não confirmado especificamente pra este modelo)',
  'Híbrido e:HEV esportivo — motor 2.0L Atkinson (gerador) + motor elétrico de tração, câmbio simulado Honda S+ Shift',
  null,
  null,
  null,
  null,
  null,
  null,
  null,
  null,
  null,
  '6 anos veículo / 8 anos sistema híbrido',
  'HEV',
  true,
  '11/09/2026',
  null,
  null,
  null,
  null,
  null,
  'EM PRÉ-VENDA até o final de setembro/2026 (anunciado no Festival Interlagos, 27/08/2026) — ainda não é venda geral pela rede de concessionárias, incluído a pedido do usuário mesmo assim por já ter preço oficial firme (R$380.000) e ser híbrido confirmado. Retorno do cupê esportivo da Honda ao Brasil, agora eletrificado, compartilhando chassi/suspensão/freios Brembo com o Civic Type R. Catálogo digital oficial da Honda (baixado em 11/09/2026) lista os componentes separados — motor 2.0L Atkinson 143cv/19,1kgf.m gasolina + motor elétrico 184cv/32,1kgf.m — exatamente os MESMOS números do Civic Advanced Hybrid, sem publicar uma "potência combinada" nessa ficha específica. Os 203cv usados aqui como potência combinada vêm de multiplas fontes de imprensa (incluindo a AutoData, publicação do setor automotivo) reportando esse valor de forma consistente — provavelmente de um press release da Honda que essa ficha de consumidor não repete. Vale reconfirmar quando a Honda publicar uma ficha técnica mais completa. Versão única, 3 cores (Crystal Black Pearl, Rallye Red, Moonlit White Pearl). Dimensões/porta-malas/peso não encontrados em nenhuma fonte oficial até 11/09/2026.',
  'https://www.honda.com.br/automoveis/sites/hab/files/2026-08/Menu_Home_Prelude_v2_1.webp',
  null,
  '{"urbano":2,"familia":1,"aventura":1,"performance":5,"custo":1}'::jsonb
)
on conflict (id) do update set
  name = excluded.name, brand = excluded.brand, category = excluded.category, price = excluded.price,
  power_cv = excluded.power_cv, torque_nm = excluded.torque_nm, battery_kwh = excluded.battery_kwh,
  battery_chem = excluded.battery_chem, motor_type = excluded.motor_type, range_km = excluded.range_km,
  accel = excluded.accel, ground_clearance = excluded.ground_clearance, trunk_l = excluded.trunk_l,
  weight_kg = excluded.weight_kg, wallbox = excluded.wallbox, ac_kw = excluded.ac_kw, dc_kw = excluded.dc_kw,
  airbags = excluded.airbags, warranty = excluded.warranty, fuel_type = excluded.fuel_type,
  verified = excluded.verified, price_verified_date = excluded.price_verified_date,
  maintenance_interval = excluded.maintenance_interval, maintenance_first_cost = excluded.maintenance_first_cost,
  maintenance_km_base = excluded.maintenance_km_base, maintenance_total_cost = excluded.maintenance_total_cost,
  consumption_kwh_100 = excluded.consumption_kwh_100, tech_notes = excluded.tech_notes,
  image_url = excluded.image_url, video_url = excluded.video_url, personas = excluded.personas;
